project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN
base_path: .
base_url: 'https://spongepowered.crowdin.com'

files:
  - source: '/build/locale/**/*.pot'
    translation: '/locale/%locale_with_underscore%/LC_MESSAGES/**/%file_name%.po'

    languages_mapping:
      locale_with_underscore:
        # Pseudo-language used for In-Context Localization
        lol: translate
